stages:
  - test
  - build
  - deploy

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install pre-commit

.test:
  stage: test
  before_script:
    - echo "Running test"
  rules:
    - if: $BUILD_ONLY == null

.build:
  stage: build
  script:
    - echo "Building Docker Image"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
  rules:
    - if: $BUILD_ONLY == null

.deploy:
  stage: deploy
  script:
    - echo "Deploying Docker Image to Cloud"
    - docker push $CI_REGISTRY_IMAGE:latest # This only push the image to the registry for now, would do AWS?
  only:
    - master

lint:
  extends: .test
  script:
    - echo "Running lint"
    - pre-commit run --all-files
  rules:
    - if: $BUILD_ONLY == null

unit_test:
  extends: .test
  script:
    - echo "Running unit_test"
    - pytest .
  rules:
    - when: on_success
    - if: $BUILD_ONLY == null